/* table to store user info */
CREATE TABLE users(
    id varchar,
    name varchar,
    description varchar,
    avatar varchar,
    email varchar,
    validated int,
    validationemail varchar,
    validationdate int,
    creationdate int,
    validationuri varchar,
    changepassword int,
    lastlogin int,
    currentloginuri varchar,
    lastpasswordchange int,
    lastemailcheck int,
    waitingforemailcheck int,
    locale varchar,
    notes varchar,
    location varchar,
    owner varchar,
    suspended int,
    blacklisted int,
    userrole varchar,
    usertypeproprietaryinfo varchar,
    securitypolicy varchar,
    securitypolicychange int,
    currentpassword varchar,
    lastpasswords varchar,
    oauthtype varchar,
    oauthuserinfo varchar,
    modified int,
    signingup varchar
);
